
blank_issues_enabled: false
contact_links:
  - name: User mailing list 
    url: https://groups.google.com/forum/#!forum/keycloak-user
    about: Ask and answer questions here 
  - name: Developer mailing list 
    url: https://groups.google.com/forum/#!forum/keycloak-dev
    about: Propose new features and join in design discussions here
