name: Keycloak CI

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
      - copilot/**
  pull_request:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"
  SUREFIRE_RERUN_FAILING_COUNT: 2
  SUREFIRE_RETRY: "-Dsurefire.rerunFailingTestsCount=2"
  KC_TEST_GITHUB_SLOW_METHOD: "10"
  KC_TEST_GITHUB_SLOW_CLASS: "60"

concurrency:
  # Only cancel jobs for PR updates
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  # Generate version compatibility matrix in a separate job to avoid multiline secret masking issues.
  version-compatibility:
    name: Version Compatibility Matrix
    uses: ./.github/workflows/version-compatibility-matrix.yml
    permissions:
      contents: read

  conditional:
    name: Check conditional workflows and jobs
    runs-on: ubuntu-latest
    outputs:
      ci: ${{ steps.conditional.outputs.ci }}
      ci-quarkus: ${{ steps.conditional.outputs.ci-quarkus }}
      ci-store: ${{ steps.conditional.outputs.ci-store }}
      ci-sssd: ${{ steps.conditional.outputs.ci-sssd }}
      ci-webauthn: ${{ steps.conditional.outputs.ci-webauthn }}
      ci-aurora: ${{ steps.auroradb-tests.outputs.run-aurora-tests }}
      ci-azure: ${{ steps.azure-tests.outputs.run-azure-tests }}
      ci-additional-dbs: ${{ steps.additional-dbs-tests.outputs.run-additional-dbs-tests }}
      ci-admin-v2: ${{ steps.conditional.outputs.admin-v2 }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - id: conditional
        uses: ./.github/actions/conditional
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: AuroraDB conditional check
        id: auroradb-tests
        run: |
          RUN_AURORADB_TESTS=false
          if [[ $GITHUB_EVENT_NAME != "pull_request" && -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then
            RUN_AURORADB_TESTS=true
          fi
          echo "run-aurora-tests=$RUN_AURORADB_TESTS" >> $GITHUB_OUTPUT

      - name: Azure conditional check
        id: azure-tests
        run: |
          RUN_AZURE_TESTS=false
          if [[ $GITHUB_EVENT_NAME != "pull_request" && -n "${{ secrets.AZURE_CREDENTIALS }}" ]]; then
            RUN_AZURE_TESTS=true
          fi
          echo "run-azure-tests=$RUN_AZURE_TESTS" >> $GITHUB_OUTPUT

      - name: Additional DBs conditional check
        id: additional-dbs-tests
        run: |
          RUN_ADDITIONAL_DBS_TESTS=false
          if [[ $GITHUB_EVENT_NAME != "pull_request" && -n "${{ secrets.PRIVATE_DBS_QUAY_USERNAME }}" && -n "${{ secrets.PRIVATE_DBS_QUAY_TOKEN }}" ]]; then
            RUN_ADDITIONAL_DBS_TESTS=true
          fi
          echo "run-additional-dbs-tests=$RUN_ADDITIONAL_DBS_TESTS" >> $GITHUB_OUTPUT


  build:
    name: Build
    if: needs.conditional.outputs.ci == 'true'
    runs-on: ubuntu-latest
    needs: conditional
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check base testsuites
        run: tests/base/check-base-suites.sh

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Spotless
        run: ./mvnw -Pdocs,distribution,operator spotless:check

      - name: Check for unstaged proto.lock files
        if: github.event_name == 'pull_request' && startsWith(github.event.pull_request.base.ref, 'release/')
        run: git diff --name-only --exit-code -- "**/proto.lock"

  base-new-integration-tests:
    name: Base IT (new)
    runs-on: ubuntu-latest
    needs:
      - build
    timeout-minutes: 45
    strategy:
      matrix:
        suite: [Base1TestSuite, Base2TestSuite]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - id: integration-test-setup
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

        # This step is necessary because test/clustering requires building a new Keycloak image built from tar.gz
        # file that is not part of m2-keycloak.tzts archive
      - name: Build tar keycloak-quarkus-dist
        run: ./mvnw package -pl quarkus/server/,quarkus/dist/

      - name: Run tests
        run: ./mvnw package -f tests/pom.xml -Dtest=${{ matrix.suite }}
