name: scan-deps-pnpm.yml
on:
  workflow_dispatch:

jobs:
  scan-pnpm-deps:
    name: Scan PNPM dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: 'js/pnpm-lock.yaml'
          format: 'sarif'
          output: 'trivy-pnpm.sarif'
          scanners: 'vuln'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-pnpm.sarif'
          category: 'trivy-pnpm'
        
