name: scan-deps-pnpm.yml
on:
  workflow_dispatch:

jobs:
  scan-pnpm-deps:
    name: Scan PNPM dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        branch: [ "main", "release/26.4", "release/26.6" ]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - run: echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: 'js/pnpm-lock.yaml'
          format: 'sarif'
          output: 'trivy-pnpm.sarif'
          scanners: 'vuln'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-pnpm.sarif'
          category: 'trivy-pnpm'
          ref: ${{ matrix.branch }}
          sha: ${{ env.CURRENT_SHA }}          
